# Generated by Django 3.2.5 on 2022-01-25 06:31

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('blood_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('Hh', 'Hh')], default=None, max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('Whole Blood', 'Whole Blood'), ('Plasma', 'Plasma'), ('Platelets', 'Platelets')], default=None, max_length=50, null=True)),
                ('acceptable_blood_group', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone', models.CharField(default='', max_length=10)),
                ('units', models.CharField(max_length=5)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('hospital_initials', models.CharField(default='', max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('urgent', models.BooleanField(blank=True, default=False)),
                ('slug', models.SlugField(default=None, max_length=400, unique=True)),
                ('custom_field_key', models.CharField(blank=True, default='', max_length=255)),
                ('custom_field_value', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Blood Request',
            },
        ),
        migrations.CreateModel(
            name='cities',
            fields=[
                ('city_id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='', max_length=100)),
                ('city_state', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.IntegerField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('date_of_birth', models.DateField(default=None)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone', models.CharField(default='', max_length=11)),
                ('pin_code', models.IntegerField(default=False)),
                ('I_agree_to_the_terms_and_conditions_stated_below', models.BooleanField(default=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-'), ('Hh', 'Hh')], default=None, max_length=4)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('designation', models.TextField(blank=True, default='', null=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to=home.models.upload_review_photo)),
                ('city', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.cities')),
                ('state', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.states')),
            ],
        ),
    ]
