# Generated by Django 3.2.5 on 2022-01-26 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodbank_name', models.CharField(default='', max_length=200)),
                ('pin_code', models.IntegerField(default=False)),
                ('contact_person', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone', models.CharField(default='', max_length=11)),
                ('I_agree_to_the_terms_and_conditions_stated_below', models.BooleanField(default=True)),
                ('city', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.cities')),
                ('state', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='home.states')),
            ],
        ),
    ]
