# Generated by Django 3.2.5 on 2024-01-21 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bankrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city_state',
        ),
        migrations.AddField(
            model_name='cities',
            name='dbid',
            field=models.IntegerField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='cities',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='state_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='states',
            name='dbid',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
