# Generated by Django 3.2.5 on 2024-01-21 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20240121_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorrequest',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cities'),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.states'),
        ),
    ]
