# Generated by Django 3.2.5 on 2022-01-27 04:26

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('introduction', models.TextField(default='')),
                ('author', models.CharField(default=None, max_length=100)),
                ('author_designation', models.TextField(default=None, max_length=100)),
                ('about_author', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('image_main', models.FileField(null=True, upload_to=blog.models.upload_location_main)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheading', models.CharField(max_length=250)),
                ('content', models.TextField(default=None)),
                ('images', models.ImageField(blank=True, default=None, upload_to=blog.models.upload_here)),
                ('caption_image', models.CharField(blank=True, default='', max_length=255)),
                ('section', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
